USE `user2daw_BD2-06`;

CREATE TABLE AdminV2 (
    id INT AUTO_INCREMENT NOT NULL ,
    correo VARCHAR(40) NOT NULL,
    pasw VARCHAR(255) NOT NULL,
    nombre VARCHAR(20) NOT NULL,
    perfil TINYINT NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB CHARSET=utf8mb4;